---
- hosts: all
  user: vagrant
  sudo: yes
  tasks:
    - name: include variables 
      include_vars: vars.yml

    - name: run apt-get update
      apt: update_cache=yes

    - name: Install required system packages
      apt: name={{ item }} state=installed
      with_items:
        - build-essential
        - libpq-dev
        - python-dev
        - python-setuptools
        - python-pip
        - git 
        - libjpeg-dev

    - name: create worker group
      user: name=worker uid=1020

    - name: create {{ site_user }} user and add to the worker group
      user: name={{ site_user }} uid=1010 groups="worker,sudo" password=$6$aPAfjl5w39XCz4qf$Yfjp5AHL1QwdYYiP6omTytTMhAt2YHYJ.yPmr2q5yI7U35fS0FLj2TSWtzL5ps8UiTjyVABkZeNxu5HmxHa33/

    - name: Create {{ site_user }} root directory and configure permissions
      file: path=/iscape/sites/{{ site_user }} state=directory owner={{ site_user }} group=worker  mode="g+s" recurse=yes

    - name: Create directory for {{ site_user }} ssh keys
      file: path=/home/{{ site_user }}/.ssh state=directory owner={{ site_user }} group={{ site_user }}

    - name: copy keys to .ssh directory
      copy: src=~/.ssh/id_rsa dest=/home/{{ site_user }}/.ssh/id_rsa mode=0600 owner={{ site_user }} group={{ site_user }}

    - name: copy keys to .ssh directory
      copy: src=~/.ssh/id_rsa.pub dest=/home/{{ site_user }}/.ssh/id_rsa.pub mode=0600 owner={{ site_user }} group={{ site_user }}         

    - name: Upgrade pip
      pip: name=pip state=latest

    - name: install virtualenv
      pip: name=virtualenv

    - name: create virtualenv
      command: virtualenv /iscape/sites/{{ site_user }}/

    - name: Create data directory
      file: path=/iscape/sites/{{ site_user }}/data state=directory

    - name: Create logging directory
      file: path=/iscape/sites/{{ site_user }}/var/log state=directory

    - name: Configure permissions again so they'll apply to the recently created directories
      file: path=/iscape/sites/{{ site_user }} owner={{ site_user }} group=worker  mode="g+s" recurse=yes

    # Setup the developer tools
    - name: include choice of dev tools
      include: flavors/dev-environments/environment.yml 
